---
input_timesteps: 5280
output_timesteps: 480
batch_size: 16
max_epochs: 10000
patience: 50
train_data:
  - [data/original2018/train_x1.wav, data/original2018/train_y1.wav]
  - [data/original2018/train_x2.wav, data/original2018/train_y2.wav]
  - [data/original2018/train_x3.wav, data/original2018/train_y3.wav]
  - [data/original2018/train_x4.wav, data/original2018/train_y4.wav]
val_data:
  - [data/original2018/val_x.wav, data/original2018/val_y.wav]
