---
sample_rate: 44100
input_timesteps: 5280
output_timesteps: 480
batch_size: 16
max_epochs: 10000
patience: 50
train_data:
  - [data/wright2019/train/muff-input.wav, data/wright2019/train/muff-target.wav]
val_data:
  - [data/wright2019/val/muff-input.wav, data/wright2019/val/muff-target.wav]
